# Generated by Django 2.2.5 on 2019-11-29 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191129_1031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Router',
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 29, 10, 38, 50, 374157)),
        ),
    ]
