# Generated by Django 2.2.5 on 2019-11-29 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191129_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 29, 10, 52, 22, 639142)),
        ),
    ]
