# Generated by Django 2.2.5 on 2019-11-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20191129_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
