# Generated by Django 2.2.5 on 2019-12-06 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20191129_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture_url',
            field=models.FileField(default=django.utils.timezone.now, upload_to='blog_pictures/'),
            preserve_default=False,
        ),
    ]
