# Generated by Django 2.2.5 on 2019-12-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture_url',
            field=models.FileField(upload_to='media/'),
        ),
    ]
