# Generated by Django 2.2.5 on 2019-12-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20191206_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture_url',
            field=models.FileField(upload_to='blog_pictures/'),
        ),
    ]
