# Generated by Django 2.2.5 on 2019-12-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20191206_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture_url',
            field=models.FileField(blank=True, null=True, upload_to='blog_pictures/'),
        ),
    ]
