# Generated by Django 2.2.5 on 2019-12-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('email', models.EmailField(max_length=254)),
                ('appointment_status', models.CharField(default='open', max_length=20)),
            ],
        ),
    ]
