# Generated by Django 2.2.5 on 2020-01-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(default='open', max_length=255),
        ),
    ]
