# Generated by Django 2.2.5 on 2020-01-14 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0002_confirmationtoken'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('appointment_date', 'appointment_time')},
        ),
    ]
