# Generated by Django 2.2.5 on 2020-01-06 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0002_auto_20200106_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='name',
        ),
    ]
