# Generated by Django 2.2.5 on 2020-01-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0004_auto_20200103_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(default='open', max_length=10),
        ),
    ]
