# Generated by Django 2.2.5 on 2020-01-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0005_auto_20200103_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='surname',
            field=models.CharField(max_length=50),
        ),
    ]
