# Generated by Django 2.2.5 on 2020-01-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0008_auto_20200103_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(max_length=15),
        ),
    ]
