# Generated by Django 2.2.5 on 2020-01-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0011_auto_20200103_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(max_length=255),
        ),
    ]
