# Generated by Django 2.2.5 on 2019-12-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20191129_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='media_description',
            field=models.CharField(default='Napisz tu coś', max_length=150),
        ),
    ]
