# Generated by Django 2.2.5 on 2019-12-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_media_media_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_url',
            field=models.FileField(upload_to='materials/'),
        ),
    ]
