# Generated by Django 2.2.5 on 2019-12-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_auto_20191206_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_url',
            field=models.FileField(upload_to='media/'),
        ),
    ]
