# Generated by Django 2.2.5 on 2019-12-05 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
